/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Selects I2C mode.: Standard GPIO functionality. Requires external pull-up for GPIO output function. */
#define PIO0_10_I2CMODE_Standard_GPIO 0x01u
/*!
 * @brief Selects I2C mode.: Standard GPIO functionality. Requires external pull-up for GPIO output function. */
#define PIO0_11_I2CMODE_Standard_GPIO 0x01u

/*! @name PIO0_4 (number 6), SW1/P3[9]/J2[7]/P0_4-ISP_U_TXD-WAKEUP
  @{ */
#define BOARD_INITPINS_CD_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CD_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_CD_PIN 4U    /*!<@brief 0U pin index: 4 */
                                    /* @} */

/*! @name PIO0_10 (number 10), P3[41]/J1[1]/P4[6]/P0_10-I2C0_SCL
  @{ */
#define BOARD_INITPINS_COD_PUSH_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_COD_PUSH_PIN 10U /*!<@brief 0U pin index: 10 */
                                        /* @} */

/*! @name PIO0_11 (number 9), P3[40]/J1[2]/P4[8]/P0_11-I2C0_SDA
  @{ */
#define BOARD_INITPINS_SWITCH_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_SWITCH_PIN 11U /*!<@brief 0U pin index: 11 */
                                      /* @} */

/*! @name PIO0_12 (number 4), SW2/D1[1]/P3[45]/J2[5]/P0_12-RED-ISP
  @{ */
#define BOARD_INITPINS_V_PEAK_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_V_PEAK_PIN 12U /*!<@brief 0U pin index: 12 */
                                      /* @} */

/*! @name PIO0_13 (number 3), P4[2]/P3[46]/J1[10]/P0_13
  @{ */
#define BOARD_INITPINS_PWM_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_PWM_PIN 13U /*!<@brief 0U pin index: 13 */
                                   /* @} */

/*! @name PIO0_14 (number 20), P3[16]/J5[2]/P0_14-ADC2-ACMP_I3
  @{ */
#define BOARD_INITPINS_RST_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_RST_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_RST_PIN 14U   /*!<@brief 0U pin index: 14 */
                                     /* @} */

/*! @name PIO0_17 (number 2), P4[4]/P3[47]/J2[1]/P0_17
  @{ */
#define BOARD_INITPINS_SDA_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_SDA_PIN 17U /*!<@brief 0U pin index: 17 */
                                   /* @} */

/*! @name PIO0_23 (number 1), P3[17]/J5[3]/P0_23-ADC3-ACMP_I4
  @{ */
#define BOARD_INITPINS_SCLK_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_SCLK_PIN 23U /*!<@brief 0U pin index: 23 */
                                    /* @} */

/*! @name PIO0_0 (number 19), P3[10]/J2[8]/P0_0-ISP_U_RXD
  @{ */
#define BOARD_INITPINS_CS0_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_CS0_PIN 0U  /*!<@brief 0U pin index: 0 */
                                   /* @} */

/*! @name PIO0_8 (number 14), P3[13]/U2[27]/P0_8-LINK_nSLEEP
  @{ */
#define BOARD_INITPINS_LED1_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_LED1_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_LED1_PIN 8U    /*!<@brief 0U pin index: 8 */
                                      /* @} */

/*! @name PIO0_9 (number 13), P3[12]/U2[26]/P0_9-LINK_nWAKE
  @{ */
#define BOARD_INITPINS_LED2_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_LED2_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_LED2_PIN 9U    /*!<@brief 0U pin index: 9 */
                                      /* @} */

/*! @name PIO0_5 (number 5), P3[44]/J2[3]/P0_28-WKTCLKIN
  @{ */
#define BOARD_INITPINS_SWRST_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_SWRST_PIN 5U  /*!<@brief 0U pin index: 5 */
                                     /* @} */

/*! @name PIO0_1 (number 12), P3[11]/P0_1-CLKIN
  @{ */
#define BOARD_INITPINS_COD_CHA_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_COD_CHA_PIN 1U  /*!<@brief 0U pin index: 1 */
                                       /* @} */

/*! @name PIO0_15 (number 11), P3[8]/J1[8]/P4[1]/P0_15-SSEL
  @{ */
#define BOARD_INITPINS_COD_CHB_PORT 0U /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_COD_CHB_PIN 15U /*!<@brief 0U pin index: 15 */
                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M0P */

#define IOCON_PIO_CLKDIV0 0x00u      /*!<@brief IOCONCLKDIV0 */
#define IOCON_PIO_HYS_DI 0x00u       /*!<@brief Disable hysteresis */
#define IOCON_PIO_INV_DI 0x00u       /*!<@brief Input not invert */
#define IOCON_PIO_MODE_PULLUP 0x10u  /*!<@brief Selects pull-up function */
#define IOCON_PIO_OD_DI 0x00u        /*!<@brief Disables Open-drain function */
#define IOCON_PIO_SMODE_BYPASS 0x00u /*!<@brief Bypass input filter */

/*! @name PIO0_12 (number 4), SW2/D1[1]/P3[45]/J2[5]/P0_12-RED-ISP
  @{ */
#define BOARD_INITLEDSPINS_V_PEAK_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITLEDSPINS_V_PEAK_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITLEDSPINS_V_PEAK_PIN 12U   /*!<@brief 0U pin index: 12 */
                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void); /* Function assigned for the Cortex-M0P */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void); /* Function assigned for the Cortex-M0P */

#define IOCON_PIO_CLKDIV0 0x00u      /*!<@brief IOCONCLKDIV0 */
#define IOCON_PIO_HYS_DI 0x00u       /*!<@brief Disable hysteresis */
#define IOCON_PIO_INV_DI 0x00u       /*!<@brief Input not invert */
#define IOCON_PIO_MODE_PULLUP 0x10u  /*!<@brief Selects pull-up function */
#define IOCON_PIO_OD_DI 0x00u        /*!<@brief Disables Open-drain function */
#define IOCON_PIO_SMODE_BYPASS 0x00u /*!<@brief Bypass input filter */

/*! @name SWCLK (number 7), P5[4]/U2[16]/TARGET_SWCLK
  @{ */
/* @} */

/*! @name SWDIO (number 8), P5[2]/U2[17]/TARGET_SWDIO
  @{ */
/* @} */

/*! @name RESETN (number 5), P3[44]/J2[3]/P0_28-WKTCLKIN
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSWD_DEBUGPins(void); /* Function assigned for the Cortex-M0P */

#define IOCON_PIO_CLKDIV0 0x00u      /*!<@brief IOCONCLKDIV0 */
#define IOCON_PIO_HYS_DI 0x00u       /*!<@brief Disable hysteresis */
#define IOCON_PIO_INV_DI 0x00u       /*!<@brief Input not invert */
#define IOCON_PIO_MODE_PULLUP 0x10u  /*!<@brief Selects pull-up function */
#define IOCON_PIO_OD_DI 0x00u        /*!<@brief Disables Open-drain function */
#define IOCON_PIO_SMODE_BYPASS 0x00u /*!<@brief Bypass input filter */

/*! @name PIO0_4 (number 6), SW1/P3[9]/J2[7]/P0_4-ISP_U_TXD-WAKEUP
  @{ */
#define BOARD_INITBUTTONSPINS_CD_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITBUTTONSPINS_CD_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITBUTTONSPINS_CD_PIN 4U    /*!<@brief 0U pin index: 4 */
                                           /* @} */

/*! @name PIO0_12 (number 4), SW2/D1[1]/P3[45]/J2[5]/P0_12-RED-ISP
  @{ */
#define BOARD_INITBUTTONSPINS_V_PEAK_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITBUTTONSPINS_V_PEAK_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITBUTTONSPINS_V_PEAK_PIN 12U   /*!<@brief 0U pin index: 12 */
                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
