/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v6.0
processor: LPC824
package_id: LPC824M201JDH20
mcu_data: ksdk2_0
processor_version: 6.0.2
pin_labels:
- {pin_num: '11', pin_signal: PIO0_15, label: 'P3[8]/J1[8]/P4[1]/P0_15-SSEL', identifier: COD_CHB}
- {pin_num: '10', pin_signal: PIO0_10/I2C0_SCL, label: 'P3[41]/J1[1]/P4[6]/P0_10-I2C0_SCL', identifier: COD_PUSH}
- {pin_num: '4', pin_signal: PIO0_12, label: 'SW2/D1[1]/P3[45]/J2[5]/P0_12-RED-ISP', identifier: V_PEAK}
- {pin_num: '7', pin_signal: SWCLK/PIO0_3, label: 'P5[4]/U2[16]/TARGET_SWCLK', identifier: DEBUG_SWD_SWDCLK}
- {pin_num: '8', pin_signal: SWDIO/PIO0_2, label: 'P5[2]/U2[17]/TARGET_SWDIO', identifier: DEBUG_SWD_SWDIO}
- {pin_num: '5', pin_signal: RESETN/PIO0_5, label: 'P3[44]/J2[3]/P0_28-WKTCLKIN', identifier: SWRST}
- {pin_num: '6', pin_signal: PIO0_4/ADC_11, label: 'SW1/P3[9]/J2[7]/P0_4-ISP_U_TXD-WAKEUP', identifier: CD}
- {pin_num: '3', pin_signal: PIO0_13/ADC_10, label: 'P4[2]/P3[46]/J1[10]/P0_13', identifier: PWM}
- {pin_num: '9', pin_signal: PIO0_11/I2C0_SDA, label: 'P3[40]/J1[2]/P4[8]/P0_11-I2C0_SDA', identifier: SWITCH}
- {pin_num: '12', pin_signal: PIO0_1/ACMP_I2/CLKIN, label: 'P3[11]/P0_1-CLKIN', identifier: COD_CHA}
- {pin_num: '13', pin_signal: PIO0_9/XTALOUT, label: 'P3[12]/U2[26]/P0_9-LINK_nWAKE', identifier: LED2}
- {pin_num: '14', pin_signal: PIO0_8/XTALIN, label: 'P3[13]/U2[27]/P0_8-LINK_nSLEEP', identifier: LED1}
- {pin_num: '19', pin_signal: PIO0_0/ACMP_I1, label: 'P3[10]/J2[8]/P0_0-ISP_U_RXD', identifier: CS0}
- {pin_num: '20', pin_signal: PIO0_14/ACMP_I3/ADC_2, label: 'P3[16]/J5[2]/P0_14-ADC2-ACMP_I3', identifier: RST}
- {pin_num: '1', pin_signal: PIO0_23/ADC_3/ACMP_I4, label: 'P3[17]/J5[3]/P0_23-ADC3-ACMP_I4', identifier: SCLK}
- {pin_num: '2', pin_signal: PIO0_17/ADC_9, label: 'P4[4]/P3[47]/J2[1]/P0_17', identifier: SDA}
- {pin_num: '15', pin_signal: VDD, label: C11/C12/FB4/VDD}
- {pin_num: '18', pin_signal: VREFP, label: C13/FB3/VREFP}
- {pin_num: '17', pin_signal: VREFN, label: FB2/VREFN}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_iocon.h"
#include "fsl_swm.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    BOARD_InitDEBUG_UARTPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '6', peripheral: GPIO, signal: 'PIO0, 4', pin_signal: PIO0_4/ADC_11, direction: OUTPUT}
  - {pin_num: '10', peripheral: PINT, signal: 'PINT, 1', pin_signal: PIO0_10/I2C0_SCL, i2cmode: gpioMode}
  - {pin_num: '9', peripheral: PINT, signal: 'PINT, 2', pin_signal: PIO0_11/I2C0_SDA, i2cmode: gpioMode}
  - {pin_num: '4', peripheral: ADC0, signal: PINTRIG0, pin_signal: PIO0_12}
  - {pin_num: '3', peripheral: SCT0, signal: 'OUT, 0', pin_signal: PIO0_13/ADC_10}
  - {pin_num: '20', peripheral: GPIO, signal: 'PIO0, 14', pin_signal: PIO0_14/ACMP_I3/ADC_2, direction: OUTPUT}
  - {pin_num: '2', peripheral: SPI0, signal: MOSI, pin_signal: PIO0_17/ADC_9, direction: OUTPUT}
  - {pin_num: '1', peripheral: SPI0, signal: SCK, pin_signal: PIO0_23/ADC_3/ACMP_I4, direction: OUTPUT}
  - {pin_num: '19', peripheral: SPI0, signal: SSEL0, pin_signal: PIO0_0/ACMP_I1, direction: OUTPUT}
  - {pin_num: '14', peripheral: GPIO, signal: 'PIO0, 8', pin_signal: PIO0_8/XTALIN, direction: OUTPUT}
  - {pin_num: '13', peripheral: GPIO, signal: 'PIO0, 9', pin_signal: PIO0_9/XTALOUT, direction: OUTPUT}
  - {pin_num: '5', peripheral: ACMP, signal: ACMP_OUT, pin_signal: RESETN/PIO0_5}
  - {pin_num: '12', peripheral: PINT, signal: 'PINT, 0', pin_signal: PIO0_1/ACMP_I2/CLKIN}
  - {pin_num: '11', peripheral: PINT, signal: 'PINT, 3', pin_signal: PIO0_15}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitPins(void)
{
    /* Enables clock for IOCON block.: Enable. */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables clock for switch matrix.: Enable. */
    CLOCK_EnableClock(kCLOCK_Swm);
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    gpio_pin_config_t CD_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_4 (pin 6)  */
    GPIO_PinInit(BOARD_INITPINS_CD_GPIO, BOARD_INITPINS_CD_PORT, BOARD_INITPINS_CD_PIN, &CD_config);

    gpio_pin_config_t LED1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_8 (pin 14)  */
    GPIO_PinInit(BOARD_INITPINS_LED1_GPIO, BOARD_INITPINS_LED1_PORT, BOARD_INITPINS_LED1_PIN, &LED1_config);

    gpio_pin_config_t gpio0_pin0_9 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_9 (pin )  */
    GPIO_PinInit(GPIO, 0U, 9U, &gpio0_pin0_9);

    gpio_pin_config_t RST_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_14 (pin 20)  */
    GPIO_PinInit(BOARD_INITPINS_RST_GPIO, BOARD_INITPINS_RST_PORT, BOARD_INITPINS_RST_PIN, &RST_config);

    IOCON->PIO[8] = ((IOCON->PIO[8] &
                      /* Mask bits to zero which are setting */
                      (~(IOCON_PIO_I2CMODE_MASK)))

                     /* Selects I2C mode.: Standard GPIO functionality. Requires external pull-up for GPIO output
                      * function. */
                     | IOCON_PIO_I2CMODE(PIO0_10_I2CMODE_Standard_GPIO));

    IOCON->PIO[7] = ((IOCON->PIO[7] &
                      /* Mask bits to zero which are setting */
                      (~(IOCON_PIO_I2CMODE_MASK)))

                     /* Selects I2C mode.: Standard GPIO functionality. Requires external pull-up for GPIO output
                      * function. */
                     | IOCON_PIO_I2CMODE(PIO0_11_I2CMODE_Standard_GPIO));

    /* ADC_PINTRIG0 connect to P0_12 */
    SWM_SetMovablePinSelect(SWM0, kSWM_ADC_PINTRIG0, kSWM_PortPin_P0_12);

    /* ACMP_OUT connect to P0_5 */
    SWM_SetMovablePinSelect(SWM0, kSWM_ACMP_OUT, kSWM_PortPin_P0_5);

    /* SPI0_SCK connect to P0_23 */
    SWM_SetMovablePinSelect(SWM0, kSWM_SPI0_SCK, kSWM_PortPin_P0_23);

    /* SPI0_MOSI connect to P0_17 */
    SWM_SetMovablePinSelect(SWM0, kSWM_SPI0_MOSI, kSWM_PortPin_P0_17);

    /* SPI0_SSEL0 connect to P0_0 */
    SWM_SetMovablePinSelect(SWM0, kSWM_SPI0_SSEL0, kSWM_PortPin_P0_0);

    /* SCT_OUT0 connect to P0_13 */
    SWM_SetMovablePinSelect(SWM0, kSWM_SCT_OUT0, kSWM_PortPin_P0_13);

    SYSCON->PINTSEL[0] = ((SYSCON->PINTSEL[0] &
                           /* Mask bits to zero which are setting */
                           (~(SYSCON_PINTSEL_INTPIN_MASK)))

                          /* Pin number select for pin interrupt or pattern match engine input. (PIO0_0 to PIO0_28
                           * correspond to numbers 0 to 28).: 0x01u */
                          | SYSCON_PINTSEL_INTPIN(0x01u));

    SYSCON->PINTSEL[1] = ((SYSCON->PINTSEL[1] &
                           /* Mask bits to zero which are setting */
                           (~(SYSCON_PINTSEL_INTPIN_MASK)))

                          /* Pin number select for pin interrupt or pattern match engine input. (PIO0_0 to PIO0_28
                           * correspond to numbers 0 to 28).: 0x0Au */
                          | SYSCON_PINTSEL_INTPIN(0x0Au));

    SYSCON->PINTSEL[2] = ((SYSCON->PINTSEL[2] &
                           /* Mask bits to zero which are setting */
                           (~(SYSCON_PINTSEL_INTPIN_MASK)))

                          /* Pin number select for pin interrupt or pattern match engine input. (PIO0_0 to PIO0_28
                           * correspond to numbers 0 to 28).: 0x0Bu */
                          | SYSCON_PINTSEL_INTPIN(0x0Bu));

    SYSCON->PINTSEL[3] = ((SYSCON->PINTSEL[3] &
                           /* Mask bits to zero which are setting */
                           (~(SYSCON_PINTSEL_INTPIN_MASK)))

                          /* Pin number select for pin interrupt or pattern match engine input. (PIO0_0 to PIO0_28
                           * correspond to numbers 0 to 28).: 0x0Fu */
                          | SYSCON_PINTSEL_INTPIN(0x0Fu));

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLEDsPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '4', peripheral: GPIO, signal: 'PIO0, 12', pin_signal: PIO0_12, direction: OUTPUT, mode: pullUp, invert: disabled, hysteresis: disabled, opendrain: disabled,
    smode: bypass, clkdiv: div0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLEDsPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitLEDsPins(void)
{
    /* Enables clock for IOCON block.: Enable. */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    gpio_pin_config_t V_PEAK_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_12 (pin 4)  */
    GPIO_PinInit(BOARD_INITLEDSPINS_V_PEAK_GPIO, BOARD_INITLEDSPINS_V_PEAK_PORT, BOARD_INITLEDSPINS_V_PEAK_PIN, &V_PEAK_config);

    const uint32_t V_PEAK = (/* Selects pull-up function */
                             IOCON_PIO_MODE_PULLUP |
                             /* Disable hysteresis */
                             IOCON_PIO_HYS_DI |
                             /* Input not invert */
                             IOCON_PIO_INV_DI |
                             /* Disables Open-drain function */
                             IOCON_PIO_OD_DI |
                             /* Bypass input filter */
                             IOCON_PIO_SMODE_BYPASS |
                             /* IOCONCLKDIV0 */
                             IOCON_PIO_CLKDIV0);
    /* PIO0 PIN12 (coords: 4) is configured as GPIO, PIO0, 12. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_12, V_PEAK);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDEBUG_UARTPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDEBUG_UARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitDEBUG_UARTPins(void)
{

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSWD_DEBUGPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '7', peripheral: SWD, signal: SWCLK, pin_signal: SWCLK/PIO0_3, mode: pullUp, invert: disabled, hysteresis: disabled, opendrain: disabled, smode: bypass,
    clkdiv: div0}
  - {pin_num: '8', peripheral: SWD, signal: SWDIO, pin_signal: SWDIO/PIO0_2, mode: pullUp, invert: disabled, hysteresis: disabled, opendrain: disabled, smode: bypass,
    clkdiv: div0}
  - {pin_num: '5', peripheral: SYSCON, signal: RESETN, pin_signal: RESETN/PIO0_5, mode: pullUp, invert: disabled, hysteresis: disabled, opendrain: disabled, smode: bypass,
    clkdiv: div0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSWD_DEBUGPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitSWD_DEBUGPins(void)
{
    /* Enables clock for IOCON block.: Enable. */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables clock for switch matrix.: Enable. */
    CLOCK_EnableClock(kCLOCK_Swm);

    const uint32_t IOCON_INDEX_PIO0_2_config = (/* Selects pull-up function */
                                                IOCON_PIO_MODE_PULLUP |
                                                /* Disable hysteresis */
                                                IOCON_PIO_HYS_DI |
                                                /* Input not invert */
                                                IOCON_PIO_INV_DI |
                                                /* Disables Open-drain function */
                                                IOCON_PIO_OD_DI |
                                                /* Bypass input filter */
                                                IOCON_PIO_SMODE_BYPASS |
                                                /* IOCONCLKDIV0 */
                                                IOCON_PIO_CLKDIV0);
    /* PIO0 PIN2 (coords: 8) is configured as SWD, SWDIO. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_2, IOCON_INDEX_PIO0_2_config);

    const uint32_t IOCON_INDEX_PIO0_3_config = (/* Selects pull-up function */
                                                IOCON_PIO_MODE_PULLUP |
                                                /* Disable hysteresis */
                                                IOCON_PIO_HYS_DI |
                                                /* Input not invert */
                                                IOCON_PIO_INV_DI |
                                                /* Disables Open-drain function */
                                                IOCON_PIO_OD_DI |
                                                /* Bypass input filter */
                                                IOCON_PIO_SMODE_BYPASS |
                                                /* IOCONCLKDIV0 */
                                                IOCON_PIO_CLKDIV0);
    /* PIO0 PIN3 (coords: 7) is configured as SWD, SWCLK. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_3, IOCON_INDEX_PIO0_3_config);

    const uint32_t IOCON_INDEX_PIO0_5_config = (/* Selects pull-up function */
                                                IOCON_PIO_MODE_PULLUP |
                                                /* Disable hysteresis */
                                                IOCON_PIO_HYS_DI |
                                                /* Input not invert */
                                                IOCON_PIO_INV_DI |
                                                /* Disables Open-drain function */
                                                IOCON_PIO_OD_DI |
                                                /* Bypass input filter */
                                                IOCON_PIO_SMODE_BYPASS |
                                                /* IOCONCLKDIV0 */
                                                IOCON_PIO_CLKDIV0);
    /* PIO0 PIN5 (coords: 5) is configured as SYSCON, RESETN. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_5, IOCON_INDEX_PIO0_5_config);

    /* SWCLK connect to P0_3 */
    SWM_SetFixedPinSelect(SWM0, kSWM_SWCLK, true);

    /* SWDIO connect to P0_2 */
    SWM_SetFixedPinSelect(SWM0, kSWM_SWDIO, true);

    /* RESETN connect to P0_5 */
    SWM_SetFixedPinSelect(SWM0, kSWM_RESETN, true);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitBUTTONsPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '6', peripheral: GPIO, signal: 'PIO0, 4', pin_signal: PIO0_4/ADC_11, direction: INPUT, mode: pullUp, invert: disabled, hysteresis: disabled, opendrain: disabled,
    smode: bypass, clkdiv: div0}
  - {pin_num: '4', peripheral: GPIO, signal: 'PIO0, 12', pin_signal: PIO0_12, direction: INPUT, mode: pullUp, invert: disabled, hysteresis: disabled, opendrain: disabled,
    smode: bypass, clkdiv: div0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBUTTONsPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitBUTTONsPins(void)
{
    /* Enables clock for IOCON block.: Enable. */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    gpio_pin_config_t CD_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_4 (pin 6)  */
    GPIO_PinInit(BOARD_INITBUTTONSPINS_CD_GPIO, BOARD_INITBUTTONSPINS_CD_PORT, BOARD_INITBUTTONSPINS_CD_PIN, &CD_config);

    gpio_pin_config_t V_PEAK_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_12 (pin 4)  */
    GPIO_PinInit(BOARD_INITBUTTONSPINS_V_PEAK_GPIO, BOARD_INITBUTTONSPINS_V_PEAK_PORT, BOARD_INITBUTTONSPINS_V_PEAK_PIN, &V_PEAK_config);

    const uint32_t V_PEAK = (/* Selects pull-up function */
                             IOCON_PIO_MODE_PULLUP |
                             /* Disable hysteresis */
                             IOCON_PIO_HYS_DI |
                             /* Input not invert */
                             IOCON_PIO_INV_DI |
                             /* Disables Open-drain function */
                             IOCON_PIO_OD_DI |
                             /* Bypass input filter */
                             IOCON_PIO_SMODE_BYPASS |
                             /* IOCONCLKDIV0 */
                             IOCON_PIO_CLKDIV0);
    /* PIO0 PIN12 (coords: 4) is configured as GPIO, PIO0, 12. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_12, V_PEAK);

    const uint32_t CD = (/* Selects pull-up function */
                         IOCON_PIO_MODE_PULLUP |
                         /* Disable hysteresis */
                         IOCON_PIO_HYS_DI |
                         /* Input not invert */
                         IOCON_PIO_INV_DI |
                         /* Disables Open-drain function */
                         IOCON_PIO_OD_DI |
                         /* Bypass input filter */
                         IOCON_PIO_SMODE_BYPASS |
                         /* IOCONCLKDIV0 */
                         IOCON_PIO_CLKDIV0);
    /* PIO0 PIN4 (coords: 6) is configured as GPIO, PIO0, 4. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_4, CD);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
